### ISSUE TITLE
Configurability of Numerizer

### ISSUE THREAD

**Issue by KritR** [jduff/numerizer#12]
I am curious to see whether we could take Numerizer into a direction that enables it for more applications than solely Chronic, while still maintaining it's functionality within Chronic.
For example, PR #5 outlines one of the issues of maintaining this pure link with Chronic.
We can also see these effects in Chronic Duration
https://github.com/henrypoydar/chronic_duration/issues/32

The main problem lies in the sense that natural language has some ambiguity and Numerizer currently is biased towards Chronic's usage.
If we could specify contexts that would allow for the calling application of Numerizer to receive the numbers back in the appropriate format that would be ideal. 
Additional context clues for processing language could also be used. For things like "a third" vs "the third" to suggest a fraction or ordinal respectively. 

I'd be willing to work on this and am very interested to hear some feedback.

**Comment by davispuh** [comment]
I would say go for it. There's no downsides for it to be configurable.

**Comment by jduff** [comment]
:+1: happy to review / take patches for some of this. I think the challenge with this is coming up with the right things to make configurable. You don’t want everything to become a setting because then it becomes complicated to use and understand, you want a small number of options that can broadly change he behavior.

At the same time I wonder if some of the pattern matching could be made smarter by getting more context from the string it is given to parse. The example from chronic duration of `half an hour` might be possible if the parser looks at everything that matches and determines the context from that. I’m pretty sure in that case the `half` just gets dropped and it uses the last match it finds.

**Comment by KritR** [comment]
I do agree that we need to limit the number of configurable options. I don't even know what a good starting point is for that. I suppose as I implement some more test cases and improve the context based parsing, we'll be able to determine the ideal set of options.

In going the more context based parsing route, depending on how complicated things get, Regex can either suffice, or things may get to the point where a tokenizer/tagger is needed, like in Chronic.

Dealing with the Chronic Duration ````half an hour````.
In terms of default behavior, should values like half & quarter be turned into their own fractions, unless preceded by another number? Is there any scenario in which that shouldn't be the case ?

**Comment by KritR** [comment]
Quick update.
So in going through and identifying ambiguous cases, there are only so many we encounter (as far as I'm aware of).

We have the Fractional vs Ordinal ordeal, of deciding when to make a value a fraction and when to make it a ordinal. 

The other two problems we face are ````seconds```` (noun-time) and ````quarter```` (noun-coin/verb). Currently numerizer won't parse ````seconds````. The only issue I foresee is if you did ````a second````, which is ambiguous. Quarter is a much trickier challenge. At present I have added it so pronouns preceding quarter(s)? result in a preservation of its original form. However, the noun version is again nearly impossible to sort out. Currently no text tagger properly figures out the context there.

As such, I'm thinking we have the following options.
````numerize ignore: ['second', 'quarter', etc]````
to maintain compatibility with chronic and provide options for other use cases
````numerize bias: :ordinal/:fractional/:none````
This should provide a widespread solution to the fractional / ordinal ordeal. I'm still thinking through implementation.

Thoughts ?
